name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checa o código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Build da aplicação com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t petfinder-api .

      # Loga no DockerHub (caso você queira usar)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pusha a imagem para o DockerHub
      - name: Push Docker image
        run: docker push your-dockerhub-username/petfinder-api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull your-dockerhub-username/petfinder-api
            docker stop petfinder-api || true
            docker rm petfinder-api || true
            docker run -d -p 8080:8080 your-dockerhub-username/petfinder-api
